# 这是存放你所有API密钥的安全保险箱
# Streamlit应用会自动从这里读取，无需暴露在主代码中

[secrets]
IPQS_API_KEY = "pGQB7wKLUMA1VxuP8mj54MKbHQPYcR6E"
IPINFO_API_KEY = "c642841fe2e55c"
SCAMALYTICS_USER = "sonicx999"
SCAMALYTICS_API_KEY = "7d32cd03e5307a930d0940084fcbdd6102de0b7fd483e9e28818ad2387edcf7d"